import { describe, it, expect, beforeAll } from "vitest";
import { commands } from "@vitest/browser/context";
import { thumbnail } from "../src/index";

// ---- Fixtures -------------------------------------------------------------

interface Fixture {
  file: string;
  mime: string;
  kind: "image" | "svg" | "pdf" | "fallback";
}

const FIXTURES: Fixture[] = [
  { file: "photo.jpg", mime: "image/jpeg", kind: "image" },
  { file: "icon.png", mime: "image/png", kind: "image" },
  { file: "animation.gif", mime: "image/gif", kind: "image" },
  { file: "vector.svg", mime: "image/svg+xml", kind: "svg" },
  { file: "landscape.webp", mime: "image/webp", kind: "image" },
  // tiny.bmp is a single-colour fixture — tested separately for dimensions only
  { file: "tiny.bmp", mime: "image/bmp", kind: "image" },
  { file: "document.pdf", mime: "application/pdf", kind: "pdf" },
  { file: "mystery.xyz", mime: "", kind: "fallback" },
];

// ---- I/O helpers ----------------------------------------------------------

async function readFixture(filename: string, mime: string): Promise<File> {
  const base64 = await commands.readFile(`./fixtures/${filename}`, "base64");
  const raw = atob(base64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  return new File([bytes], filename, { type: mime });
}

async function writeOutput(filename: string, blob: Blob): Promise<void> {
  const buffer = await blob.arrayBuffer();
  const bytes = new Uint8Array(buffer);
  const CHUNK = 8192;
  let binary = "";
  for (let i = 0; i < bytes.length; i += CHUNK) {
    binary += String.fromCharCode(
      ...bytes.subarray(i, Math.min(i + CHUNK, bytes.length)),
    );
  }
  await commands.writeFile(`./output/${filename}`, btoa(binary), "base64");
}

// ---- Pixel analysis -------------------------------------------------------

function uniqueColourBuckets(canvas: HTMLCanvasElement): number {
  const ctx = canvas.getContext("2d")!;
  const data = ctx.getImageData(0, 0, canvas.width, canvas.height).data;
  const buckets = new Set<number>();
  for (let i = 0; i < data.length; i += 4) {
    const r = data[i] >> 4;
    const g = data[i + 1] >> 4;
    const b = data[i + 2] >> 4;
    buckets.add((r << 8) | (g << 4) | b);
  }
  return buckets.size;
}

// ---- HTML index page ------------------------------------------------------

function buildIndexHtml(
  results: { fixture: string; outputName: string }[],
): string {
  const cells = results
    .map(
      (r) =>
        `<td style="text-align:center;padding:8px">` +
        `<img src="${r.outputName}" style="max-width:256px;max-height:360px;border:1px solid #ddd;border-radius:4px" />` +
        `<br/><code style="font-size:11px;color:#666">${r.fixture}</code></td>`,
    )
    .join("\n    ");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>thumbnailjs — visual snapshots</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 24px; background: #fafafa; }
    h1 { font-size: 20px; margin-bottom: 4px; }
    p { color: #666; font-size: 14px; margin-bottom: 16px; }
    table { border-collapse: collapse; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    th { background: #f5f5f5; padding: 10px 12px; text-align: center; font-size: 12px; text-transform: uppercase; color: #888; border-bottom: 1px solid #eee; }
    td { border-bottom: 1px solid #f0f0f0; }
    tr:last-child td { border-bottom: none; }
    img { display: block; margin: 0 auto; background: repeating-conic-gradient(#e8e8e8 0% 25%, transparent 0% 50%) 50% / 12px 12px; }
  </style>
</head>
<body>
  <h1>thumbnailjs — visual snapshots</h1>
  <p>Generated by <code>test/snapshots.test.ts</code>. One thumbnail per fixture at width 256.</p>
  <table>
    <tr>
    ${cells}
    </tr>
  </table>
</body>
</html>`;
}

// ===========================================================================
// Tests
// ===========================================================================

describe("render correctness", () => {
  beforeAll(() => {
    thumbnail.reset();
  });

  // ---- Images: real rendered content, many colours, correct dimensions ----

  // Exclude tiny.bmp — it's a single-colour fixture with only 1 colour bucket.
  // Still a real render, just not useful for the bucket heuristic.
  const imageFixtures = FIXTURES.filter(
    (f) => f.kind === "image" && f.file !== "tiny.bmp",
  );

  for (const fixture of imageFixtures) {
    it(`${fixture.file} → real image content`, async () => {
      const file = await readFixture(fixture.file, fixture.mime);
      const canvas = (await thumbnail(file, {
        width: 256,
        format: "canvas",
      })) as HTMLCanvasElement;

      expect(canvas.width).toBe(256);
      expect(canvas.height).toBeGreaterThan(0);

      const buckets = uniqueColourBuckets(canvas);
      expect(
        buckets,
        `${fixture.file}: uniqueColourBuckets=${buckets}, expected >10 for real image content`,
      ).toBeGreaterThan(10);
    });
  }

  it("tiny.bmp → real image content (single-colour fixture)", async () => {
    const file = await readFixture("tiny.bmp", "image/bmp");
    const canvas = (await thumbnail(file, {
      width: 256,
      format: "canvas",
    })) as HTMLCanvasElement;

    expect(canvas.width).toBe(256);
    expect(canvas.height).toBeGreaterThan(0);
  });

  // ---- SVG ----------------------------------------------------------------

  it("vector.svg → real SVG content", async () => {
    const file = await readFixture("vector.svg", "image/svg+xml");
    const canvas = (await thumbnail(file, {
      width: 256,
      format: "canvas",
    })) as HTMLCanvasElement;

    expect(canvas.width).toBe(256);
    expect(canvas.height).toBeGreaterThan(0);

    const buckets = uniqueColourBuckets(canvas);
    expect(
      buckets,
      `vector.svg: uniqueColourBuckets=${buckets}, expected >10`,
    ).toBeGreaterThan(10);
  });

  // ---- PDF: portrait, many colours ----------------------------------------

  it("document.pdf → real rendered page (portrait, many colours)", async () => {
    const file = await readFixture("document.pdf", "application/pdf");
    const canvas = (await thumbnail(file, {
      width: 256,
      format: "canvas",
    })) as HTMLCanvasElement;

    expect(canvas.width).toBe(256);
    expect(canvas.height).toBeGreaterThan(0);

    // PDFs are portrait — taller than wide when rendered with auto-height
    expect(
      canvas.height,
      `PDF canvas is ${canvas.width}x${canvas.height} — expected taller than wide`,
    ).toBeGreaterThan(canvas.width);

    const buckets = uniqueColourBuckets(canvas);
    expect(
      buckets,
      `document.pdf: uniqueColourBuckets=${buckets}, expected >10 for real PDF render`,
    ).toBeGreaterThan(10);
  });

  // ---- Fallback: unregistered format → square, flat colours ---------------

  it("mystery.xyz → fallback icon (square, few colours)", async () => {
    const file = await readFixture("mystery.xyz", "");
    const canvas = (await thumbnail(file, {
      width: 256,
      format: "canvas",
    })) as HTMLCanvasElement;

    // Fallback is always square when height is auto
    expect(canvas.width).toBe(256);
    expect(canvas.height).toBe(256);

    const buckets = uniqueColourBuckets(canvas);
    expect(
      buckets,
      `mystery.xyz: uniqueColourBuckets=${buckets}, expected <20 for flat fallback`,
    ).toBeLessThan(20);
  });

  // ---- Cross-check: different images produce different thumbnails ---------

  it("different source images produce visually distinct thumbnails", async () => {
    const photoFile = await readFixture("photo.jpg", "image/jpeg");
    const landscapeFile = await readFixture("landscape.webp", "image/webp");

    const photoCanvas = (await thumbnail(photoFile, {
      width: 128,
      height: 128,
      fit: "cover",
      format: "canvas",
    })) as HTMLCanvasElement;

    const landscapeCanvas = (await thumbnail(landscapeFile, {
      width: 128,
      height: 128,
      fit: "cover",
      format: "canvas",
    })) as HTMLCanvasElement;

    const pCtx = photoCanvas.getContext("2d")!;
    const lCtx = landscapeCanvas.getContext("2d")!;
    const pPixel = pCtx.getImageData(64, 64, 1, 1).data;
    const lPixel = lCtx.getImageData(64, 64, 1, 1).data;

    const diff =
      Math.abs(pPixel[0] - lPixel[0]) +
      Math.abs(pPixel[1] - lPixel[1]) +
      Math.abs(pPixel[2] - lPixel[2]);

    expect(
      diff,
      "photo.jpg and landscape.webp produced identical centre pixels — they may both be fallback icons",
    ).toBeGreaterThan(10);
  });
});

// ===========================================================================
// Visual snapshots — one thumbnail per fixture, written to test/output/
// ===========================================================================

describe("visual snapshots", () => {
  const allResults: { fixture: string; outputName: string }[] = [];

  beforeAll(() => {
    thumbnail.reset();
  });

  for (const fixture of FIXTURES) {
    const basename = fixture.file.replace(/\.[^.]+$/, "");

    it(`${fixture.file} → writes thumbnail to disk`, async () => {
      const file = await readFixture(fixture.file, fixture.mime);
      const result = (await thumbnail(file, { width: 256 })) as Blob;

      expect(result).toBeInstanceOf(Blob);
      expect(result.size).toBeGreaterThan(0);
      expect(result.type).toBe("image/png");

      const outputName = `${basename}-256w.png`;
      await writeOutput(outputName, result);
      allResults.push({ fixture: fixture.file, outputName });
    });
  }

  it("writes index.html for visual review", async () => {
    const html = buildIndexHtml(allResults);
    await commands.writeFile("./output/index.html", html, "utf-8");
  });
});
